version: '3.8'

services:
  calibre-web:
    image: ahedkhatib/calibre-web:65
    ports:
      - "8083:8083"
    volumes:
      - C:\Users\2020\Desktop\library:/app/library
    depends_on:
      - counter-service

  counter-service:
    image: ahedkhatib/counter-service:65
    ports:
      - "5000:5000"
    volumes:
      - C:\Users\2020\Desktop\library:/app/library
