name: Build and Push

on:
  push:

jobs:
  lint-and-test:
    name: Test on Ubunto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Flake8
        run: |
          pip install --no-cache-dir flake8

      - name: Install dependencies from requirements.txt
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Install dependencies from counterService requirements.txt
        run: |
          pip install --no-cache-dir -r counterService/requirements.txt

      - name: Install httpx
        run: |
          pip install --no-cache-dir httpx

      # Install pip and pytest
      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run Linting (Flake8)
        run: |
          flake8 --max-line-length=88 --ignore=E203,W503 . || true

      - name: Run Specific Unit Test (test_helpers.py)
        run: |
          pytest test/test_helpers.py --doctest-modules --junitxml=test-results/test_helpers.xml

      - name: Run Unit Tests for Counter Service
        run: |
          pytest test/test_counter_service.py --doctest-modules --junitxml=test-results/test_counter_service.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
           test-results/**/*.xml

  docker-build-push:
    needs: lint-and-test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ahedkhatib/calibre-web:${{ github.run_number }} .

      - name: Push Docker image to DockerHub
        run: |
          docker push ahedkhatib/calibre-web:${{ github.run_number }}


      # Build and push counter-service microservice
      - name: Build Docker image for counter-service
        run: |
          docker build -t ahedkhatib/counter-service:${{ github.run_number }} ./counterService

      - name: Push Docker image for counter-service
        run: |
          docker push ahedkhatib/counter-service:${{ github.run_number }}
