name: Build and Push

on: [push, pull_request]

jobs:
  lint-and-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Flake8
        run: |
          pip install --no-cache-dir flake8

      - name: Run Linting (Flake8)
        run: |
          flake8 --max-line-length=88 --ignore=E203,W503 . || true

  docker-build-push:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ahedkhatib/calibre-web:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push ahedkhatib/calibre-web:latest

  TriggerUITesting:
    runs-on: ubuntu-latest
    env:
      SPOTIFY_TESTING_REPO_NAME: ahedkhatib/TestAutomationProject
      UI_TESTING_WORKFLOW_ID: smoke_testing.yaml
    steps:
      - name: Trigger the Selenium testing workflow
        run: |
          curl -X POST \
           -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_GITHUB }}" \
           -H "Accept: application/vnd.github.v3+json" \
           -d "{\"ref\": \"main\", \"inputs\": {\"chrome_131_0\": true}}" \
           https://api.github.com/repos/$SPOTIFY_TESTING_REPO_NAME/actions/workflows/$UI_TESTING_WORKFLOW_ID/dispatches
