name: Test JMeter Action

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Ensure reports folder exists
        run: mkdir -p reports  # Ensures folder exists before running JMeter

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: test/calibre-standard-users.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: reports/
